version: '2'

services:

  nginx:
    image: armhfbuild/nginx
    container_name: nginx
    volumes:
      - nginx_vhosts:/etc/nginx/vhost.d:ro
      - nginx_conf:/etc/nginx/conf.d:ro
      - nginx_certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    network_mode: bridge
    restart: unless-stopped

  docker-gen-nginx:
    image: armhfbuild/docker-gen
    container_name: docker-gen-nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - templates:/etc/docker-gen/templates
    volumes_from: 
      - nginx:rw
    network_mode: none
    command: "-notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    restart: unless-stopped

  owncloud:
    image: armhf-owncloud:9.1-apache
    container_name: owncloud
    environment:
      - VIRTUAL_HOST=your.domain.com
      - CERT_NAME=shared
    volumes:
      - /var/www/html/apps
      - /var/www/html/data
      - /var/www/html/config
    network_mode: bridge
    restart: unless-stopped

volumes:
  nginx_vhosts:
    external: yes
  nginx_conf:
    external: yes
  nginx_certs:
    external: yes
  templates:
    external: yes
