version: '2'

services:

  nginx:
    image: armhfbuild/nginx
    container_name: nginx
    volumes:
      - nginx_vhosts:/etc/nginx/vhost.d:ro
      - nginx_conf:/etc/nginx/conf.d:ro
      - nginx_certs:/etc/nginx/certs:ro
      - letsencrypt_html:/usr/share/nginx/html:ro
      - owncloud_html:/var/www/html:ro
      - ttrss_ttrss_var_www_html:/var/www/html-ttrss:ro
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    network_mode: bridge
    restart: unless-stopped

  nginx-docker-gen:
    image: armhf/docker-gen
    container_name: nginx-docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - templates:/etc/docker-gen/templates:ro
      - nginx_vhosts:/etc/nginx/vhost.d:ro
      - nginx_conf:/etc/nginx/conf.d:rw
      - nginx_certs:/etc/nginx/certs:ro
    network_mode: bridge
    command: "-notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    restart: unless-stopped

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:armhf
    container_name: nginx-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_vhosts:/etc/nginx/vhost.d:rw
#      - letsencrypt_html:/usr/share/nginx/html
    volumes_from:
    - nginx:rw
    network_mode: bridge
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen-nginx
      - NGINX_PROXY_CONTAINER=nginx
    restart: unless-stopped


  owncloud:
    image: armhf-owncloud:9.1.6-fpm
    container_name: owncloud
    environment:
    - VIRTUAL_HOST=your.domain.com
    - CERT_NAME=shared
    - VIRTUAL_PROTO=fpm
    - APP_LOCATION=/var/www/html
    volumes:
    - owncloud_html:/var/www/html
    - owncloud_data:/var/www/html/data
    - owncloud_config:/var/www/html/config
    network_mode: bridge
    restart: unless-stopped

volumes:
  nginx_vhosts:
    external: yes
  nginx_conf:
    external: yes
  nginx_certs:
    external: yes
  letsencrypt_html:
  owncloud_html:
  owncloud_data:
    external: yes
  owncloud_config:
    external: yes
  templates:
    external: yes
  ttrss_ttrss_var_www_html:
    external: yes

# TODO: Can /var/run/docker.sock be made a volume?