version: '2'

services:

  nginx:
    image: armhfbuild/nginx
    container_name: nginx
    volumes:
      - /d/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - /d/nginx/conf.d:/etc/nginx/conf.d
      - /d/nginx/certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    network_mode: bridge
    restart: unless-stopped

  docker-gen-nginx:
    image: armhfbuild/docker-gen
    container_name: docker-gen-nginx
    volumes:
      - /d/docker-gen/templates:/etc/docker-gen/templates:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from: 
      - nginx
    network_mode: none
    command: "-notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    restart: unless-stopped
  
  owncloud:
    image: armhf-owncloud:9.1-apache
    container_name: owncloud
    environment:
      - VIRTUAL_HOST=${OWNCLOUD_DOMAIN}
      - CERT_NAME=shared
    volumes:
      - /d/oc/apps:/var/www/html/apps
      - /d/oc/data:/var/www/html/data
      - /d/oc/config:/var/www/html/config
    network_mode: bridge
    restart: unless-stopped

